# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1phUthE_Dk9k0LzHT4jLRyh9gf8aWfndF
"""

#refazer foi o jeito que encontrei(chatgpt) para repetir o ciclo junto do while
refazer = 's'

while refazer.lower() == 's':

# tive a ideia de interagir com o publico pedindo o nome e os dois valores que iremos utilizar

    nome = input('Digite seu nome:')
    num1 = float(input('Digite o primeiro numero:'))
    num2 = float(input('Digite o segundo numero:'))

#primeiramente havia feito apenas com os nomes porem ficou meio sujo o codigo, sendo assim utilizei uma numeração 1-4

    print('\nEscolha uma operação:')
    print('1 - Adição')
    print('2 - Subtração')
    print('3 - Multiplicação')
    print('4 - Divisão')

    operacao = input('Digite o número da operação desejada: ')

# == recebe a escolha do usuario e realiza todo o processo.

    if operacao == '1':
        print(f"Ola! {nome}, Resultado da adição: {num1} + {num2} = {num1 + num2}")
    elif operacao == '2':
        print(f"Ola! {nome}, Resultado da subtração: {num1} - {num2} = {num1 - num2}")
    elif operacao == '3':
        print(f"Ola! {nome}, Resultado da multiplicação: {num1} * {num2} = {num1 * num2}")
    elif operacao == '4':
        if num2 != 0:
            print(f"Ola! {nome}, Resultado da divisão: {num1} / {num2} = {num1 / num2}")
	#  Caso o usuario insria uma divisao por zero o sistema apresenta o erro e finaliza o codigo apresentando a opção de refazer.

        else:
            print(f"Ola! {nome}, Erro: divisão por zero não permitida.")
	# caso a opção seja invalida por exemplo escolher um numero invalido ou digitar o nome da operação o codigo é 'resetado'.
    else:
        print(f"Ola! {nome}, Opção inválida. Por favor, escolha uma operação válida.")

    refazer = input('Deseja refazer a operação? (s/n): ')

print('Fim do calculo!')
